shop/apps/core/urls.py
from django.contrib import admin
from django.urls import path

from .views import index, category_list, category_detail, product_list, product_detail


app_name = 'core'


urlpatterns = [
    path('', index, name='index'),
    path('categories/', category_list, name='category_list'),
    path('categories/<slug>/', category_detail, name='category_detail'),
    path('products/', product_list, name='product_list'),
    path('products/<slug_category>/<pk>/', product_detail, name='product_detail')
]

shop/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls', namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

shop/apps/core/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(allow_unicode=True, blank=True, default='')

    class Meta():
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:category_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)


class Tag(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=255, verbose_name='Название', help_text='max length - 255', unique=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    tag = models.ManyToManyField(Tag)
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(verbose_name="Изображение", blank=True, null=True, upload_to='product')
    price = models.FloatField()
    discount = models.FloatField(verbose_name='Скидка', validators=[MinValueValidator(0.0), MaxValueValidator(100.0)],
                                 default=0, blank=True, )
    bonus = models.PositiveIntegerField(verbose_name="Бонус", blank=True, null=True,
                                        validators=[MaxValueValidator(100)])
    in_stock = models.BooleanField(verbose_name="В наличии", default=True)
    created_dt = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)
    update_dt = models.DateTimeField(verbose_name="Дата изменения", auto_now=True)

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['-pk', ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('core:product_detail', kwargs={'slug_category': self.category.slug, 'pk': self.pk})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

shop/apps/core/views.py
from django.shortcuts import render
from .models import Category, Product, Tag


def index(request):
    context = {}
    category_qs = Category.objects.all()
    product_qs = Product.objects.all().order_by('title')[:3]

    context['category_list'] = category_qs
    context['product_list'] = product_qs

    return render(request, 'core/index.html', context)


def category_list(request):
    context = {}
    category_qs = Category.objects.all()
    context['category_list'] = category_qs
    return render(request, 'core/category_list.html', context)


def category_detail(request, slug):
    context = {}
    category = Category.objects.filter(slug=slug).first()
    context['category'] = category
    print(category)
    return render(request, 'core/category.html', context)


def product_list(request):
    context = {}
    product_qs = Product.objects.all()
    context['product_list'] = product_qs
    return render(request, 'core/product_list.html', context)


def product_detail(request, slug_category, pk):
    context = {}
    product = Product.objects.filter(pk=pk).first()
    context['product'] = product
    print(product)
    return render(request, 'core/product.html', context)

    # for category in category_qs:
    #     print('category', category.title)
    #     for product in category.product_set.all():
    #         print(product.title)

shop/shop/templates/base.html
{% load static %}
<html>
<head>
    {% include 'core/components/header.html' %}
</head>

<body>
    <main>
        {% block nav %}
        {% endblock nav %}
        {% block main %}
        {% endblock main %}
    </main>

    <footer>
        {% include 'core/components/footer.html' %}
    </footer>
</body>
</html>

shop/shop/templates/core/1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <p>Categories</p>
                <ul>
                    {% for category in category_list %}
                        Products: {{ category.title }}
                        {% for product in category.product_set.all %}
                            <li>{{ product.title }}, {{ product.price }}. {{ product.category.title }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>

                <p>Products</p>
                <ul>
                    {% for product in product_list %}
                    <li>{{ product.title }}, {{ product.price }}. {{ product.category.title }}</li>
                        {% for tag in product.tag.all %}
                            {{ tag }},
                        {% endfor %}
                    {% endfor %}
                </ul>
</body>
</html>

shop/shop/templates/core/category.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
<div class="container">
      <div class="row">
        <div class="col">
            <a>{{ category.get_absolute_url }}</a>
            <h1>{{ category.title }}</h1>
            {% for category in category_list %}
                <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
            {% endfor %}
        </div>
      </div>
    </div>

<div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for product in category.products.all %}
        <div class="col">
          <div class="card shadow-sm">

            <img src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">{{ product.title }}</p>
              <p class="card-text">{{ product.price }}</p>
              <p class="card-text">{{ product.description }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Buy</button>
                </div>
                <small class="text-muted">{{ product.update_dt }}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock main %}

shop/shop/templates/core/category_list.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
<div class="container">
    <div class="row">
      <div class="col">
        {% for category in category_list %}
            <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
        {% endfor %}
      </div>
    </div>
</div>
{% endblock main %}

shop/shop/templates/core/components/footer.html
<div class="p"></div>
<div class="container">
  <footer class="footer">
    <div class="row">
      <div class="col-2">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>

      <div class="col-2">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>

      <div class="col-4 offset-1">
        <h5>Section</h5>
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
          <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
        </ul>
      </div>
    </div>
  </footer>
</div>

shop/shop/templates/core/components/header.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Shop Category</title>
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap-grid.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap.css.map' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap-grid.css.map' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap.min.css.map' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap-grid.min.css.map' %}" rel="stylesheet" type="text/css">

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js.map' %}"></script>
</head>
<body>
{% block nav %}
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'core:index' %}">Shop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'core:product_list' %}">All Products</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'core:category_list' %}">Categories</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
<div class="p"></div>
{% endblock nav %}
</body>

shop/shop/templates/core/index.html
{% extends 'base.html' %}
{% load static %}



    {% block nav %}
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'core:index' %}">Shop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'core:product_list' %}">All Products</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'core:category_list' %}">Categories</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% endblock nav %}

    {% block main %}

    <div class="container">
      <div class="row">
        <div class="col">
            {% for category in category_list %}
                <a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
            {% endfor %}
        </div>
      </div>
    </div>

    <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for product in product_list %}
        <div class="col">
          <div class="card shadow-sm">

            <img src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">{{ product.title }}</p>
              <p class="card-text">{{ product.price }}</p>
              <a href="{{ product.get_absolute_url }}">More</a>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Buy</button>
                </div>
                <small class="text-muted">{{ product.update_dt }}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>
    </div>
    </div>
    {% endblock main %}

shop/shop/templates/core/product.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

<div class="container">
      <div class="row">
        <div class="col">
            <h1>{{ product.title }}</h1>
            <p class="card-text">{{ product.description }}</p>
        </div>
      </div>
    </div>

{% endblock main %}

shop/shop/templates/core/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block main %}
<div class="container">
    <div class="row">
      <div class="col">
        {% for product in product_list %}
            <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
        {% endfor %}
      </div>
    </div>
</div>
{% endblock main %}